runtime: go
api_version: go1

handlers:
- url: /passwords
  static_files: dart/build/passwords.html
  upload: dart/build/passwords.html
  secure: always
- url: /hooggaa
  static_files: dart/build/hooggaa.html
  upload: dart/build/hooggaa.html
  secure: always
- url: /
  static_dir: dart/build/
  secure: always
- url: /.*
  script: _go_app
  secure: always

