runtime: go111

handlers:
- url: /spelling-bee
  static_files: dart/build/spelling_bee.html
  upload: dart/build/spelling_bee.html
  secure: always
- url: /passwords
  static_files: dart/build/passwords.html
  upload: dart/build/passwords.html
  secure: always
- url: /hooggaa
  static_files: dart/build/hooggaa.html
  upload: dart/build/hooggaa.html
  secure: always
- url: /pomodoro
  static_files: dart/build/pomodoro.html
  upload: dart/build/pomodoro.html
  secure: always
- url: /css
  static_dir: dart/build/css/
  secure: always
- url: /scripts
  static_dir: dart/build/scripts/
  secure: always
- url: /assets
  static_dir: dart/build/assets/
  secure: always
- url: /
  static_files: dart/build/index.html
  upload: dart/build/index.html
  secure: always
- url: /.*
  script: _go_app
  secure: always

