name: cdn

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: '<2.0.0'
  build_web_compilers: '<3.0.0'

dependencies:
  # hooggaa dependancies
  googleapis: any
  googleapis_auth: any
